services:
  web:
    build: ./docker-images/nginx
    ports:
      - ${SITE_PORT}:80
    environment:
      SERVER_NAME: progress.local
    volumes:
      - .:/var/www
    links:
      - php
    depends_on:
      - php
  php:
    build: ./docker-images/app
    working_dir: /var/www
    environment:
      docker: "true"
    ports:
      - "9000:9000"
    links:
      - ${MYSQL_HOST}:db
    volumes:
      - .:/var/www
  db:
      image: mysql:8.0
      restart: always
      environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      volumes:
          - ./${MYSQL_DIR}:/var/lib/mysql
      ports:
          - ${MYSQL_PORT}:3306
